[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
serde-wasm-bindgen = "0.4.5"
flate2 = "1.0"

[lib]
crate-type = ["cdylib", "rlib"]
