x-variables:
  image-name: &image-name etf-matcher:latest

x-base-service: &base-service
  image: *image-name
  build:
    context: .
    dockerfile: Dockerfile
    args:
      UID: ${UID:-1000} # Default to 1000 if UID is not set
      GID: ${GID:-1000} # Default to 1000 if GID is not set
  environment:
    - FORCE_COLOR=1
  user: "${UID:-1000}:${GID:-1000}" # Use default values if not set

x-base-dev-service: &base-dev-service
  <<: *base-service
  volumes:
    - .:/app
  environment:
    - RUST_BACKTRACE=1
    - FORCE_COLOR=1

services:
  # Generate a production build
  #   Command: "docker compose build build-dist && docker compose up build-dist"
  #
  build-dist:
    <<: *base-service
    # TODO: Only mount `dist`
    volumes:
      - .:/app
    command: |
      sh -c '
      cp -rT /build_artifacts/public/pkg /app/public/pkg &&
      cp -rT /build_artifacts/public/data /app/public/data &&
      npm install &&
      npm run build
      '
    profiles:
      # Don't run by default
      - production-build

  # --- The following are used for development environments

  dev:
    <<: *base-dev-service
    ports:
      - "8000:8000"
    entrypoint: ["/usr/bin/tini", "--"]
    command: |
      sh -c '
      if [ ! -d "/app/public/pkg" ]; then
        cp -rT /build_artifacts/public/pkg /app/public/pkg;
      fi &&
      if [ ! -d "/app/public/data" ]; then
        cp -rT /build_artifacts/public/data /app/public/data;
      fi &&
      npm install &&
      npm run dev
      '

  # Used for Rust auto-refresh (not quite HMR, but close)
  dev-rust-hmr:
    <<: *base-dev-service
    depends_on:
      - dev
    # Note: The convoluted code in here skips copying over backend files
    # that already exist
    command: |
      sh -c '
      find /build_artifacts/backend -type f | while read file; do
        dest="/app/backend/$${file#/build_artifacts/backend/}"
        if [ ! -e "$$dest" ]; then
          mkdir -p "$$(dirname "$$dest")"
          cp "$$file" "$$dest"
        fi
      done &&
      find /build_artifacts/backend -type d | while read dir; do
        dest="/app/backend/$${dir#/build_artifacts/backend/}"
        if [ ! -d "$$dest" ]; then
          mkdir -p "$$dest"
        fi
      done &&
      ./docker_build_helpers/inotify_rust.sh
      '

  dev-import:
    <<: *base-dev-service
    command: "import_datapacks"
    profiles:
      # Don't run by default
      - import

  dev-build-rust:
    <<: *base-dev-service
    command: "build_rust_frontend"
    profiles:
      # Don't run by default
      - build_rust_frontend

  # TODO: This should also test the Rust
  dev-test:
    <<: *base-dev-service
    command: |
      sh -c '
      cp -rT /build_artifacts/public/pkg /app/public/pkg &&
      cp -rT /build_artifacts/public/data /app/public/data &&
      npm install &&
      npm run test:ci
      '
    profiles:
      # Don't run by default
      - test

  # TODO: This should also lint the Rust
  dev-lint:
    <<: *base-dev-service
    command: |
      sh -c '
      cp -rT /build_artifacts/public/pkg /app/public/pkg &&
      cp -rT /build_artifacts/public/data /app/public/data &&
      npm install &&
      npm run lint
      '
    profiles:
      # Don't run by default
      - lint
