x-variables:
  image-name: &image-name rust-dev-app:latest

services:
  # Generate a production build
  #   Command: "docker compose up build-dist"
  #
  build-dist:
    image: *image-name
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # Mount so we can access the build files
    command: |
      sh -c '
      cp -rT /build_artifacts/public/pkg /app/public/pkg &&
      cp -rT /build_artifacts/public/data /app/public/data &&
      npm install &&
      vite build
      '
    profiles:
      # Don't run by default
      - production-build

  # --- The following is used for development environments

  dev:
    image: *image-name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: ["/usr/bin/tini", "--"]
    command: |
      sh -c '
      cp -r /build_artifacts/.env /app/.env &&
      cp -rT /build_artifacts/public/pkg /app/public/pkg &&
      cp -rT /build_artifacts/public/data /app/public/data &&
      npm install &&
      vite serve --host 0.0.0.0 --port 8000
      '
    environment:
      - RUST_BACKTRACE=1

  # Used for Rust auto-refresh (not quite HMR, but close)
  dev-rust-hmr:
    image: *image-name
    volumes:
      - .:/app
    command: |
      sh -c '
      cp -rTf /build_artifacts/backend /app/backend/ &&
      ./docker_build_helpers/inotify_rust.sh
      '
    environment:
      - RUST_BACKTRACE=1
