x-variables:
  image-name: &image-name rust-dev-app:latest

services:
  # Generate a production build
  #   Command: "docker compose build build-dist && docker compose up build-dist"
  #
  build-dist:
    image: *image-name
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # Mount so we can access the build files
    command: |
      sh -c '
      cp -rT /build_artifacts/public/pkg /app/public/pkg &&
      cp -rT /build_artifacts/public/data /app/public/data &&
      npm install &&
      npm run build
      '
    profiles:
      # Don't run by default
      - production-build

  # --- The following is used for development environments

  dev:
    image: *image-name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: ["/usr/bin/tini", "--"]
    command: |
      sh -c '
      cp -r /build_artifacts/.env /app/.env &&
      cp -rT /build_artifacts/public/pkg /app/public/pkg &&
      cp -rT /build_artifacts/public/data /app/public/data &&
      npm install &&
      npm run dev
      '
    environment:
      - RUST_BACKTRACE=1

  # Used for Rust auto-refresh (not quite HMR, but close)
  dev-rust-hmr:
    image: *image-name
    depends_on:
      - dev
    volumes:
      - .:/app
    # Note: The convoluted code in here skips copying over backend files
    # that already exist
    command: |
      sh -c '
      find /build_artifacts/backend -type f | while read file; do
        dest="/app/backend/$${file#/build_artifacts/backend/}"
        if [ ! -e "$$dest" ]; then
          mkdir -p "$$(dirname "$$dest")"
          cp "$$file" "$$dest"
        fi
      done &&
      find /build_artifacts/backend -type d | while read dir; do
        dest="/app/backend/$${dir#/build_artifacts/backend/}"
        if [ ! -d "$$dest" ]; then
          mkdir -p "$$dest"
        fi
      done &&
      ./docker_build_helpers/inotify_rust.sh
      '
    environment:
      - RUST_BACKTRACE=1
