version: "3.8"

x-variables:
  image-name: &image-name rust-dev-app:latest

services:
  dev:
    image: *image-name
    build:
      context: .
      dockerfile: Dockerfile
      # target: final
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: ["/usr/bin/tini", "--"]
    command: |
      sh -c '
      rm -rf /app/public/pkg /app/public/data || true &&
      cp -r /build_artifacts/.env /app/.env &&
      cp -r /build_artifacts/pkg /app/public/pkg &&
      cp -r /build_artifacts/data /app/public/data &&
      npm install &&
      vite serve --host 0.0.0.0 --port 8000
      '
    environment:
      - RUST_BACKTRACE=1

  # Used for Rust auto-refresh (not quite HMR, but close)
  dev-rust-hmr:
    image: *image-name
    volumes:
      - .:/app
    command: |
      sh -c '
      ./docker_build_helpers/inotify_rust_frontend.sh
      '
    environment:
      - RUST_BACKTRACE=1

  # docker compose up build-dist
  build-dist:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: |
      sh -c '
      rm -rf /app/public/pkg /app/public/data || true &&
      cp -r /build_artifacts/pkg /app/public/pkg &&
      cp -r /build_artifacts/data /app/public/data &&
      npm install &&
      vite build
      '
    profiles:
      # Don't run by default
      - optional
